spring:

  ai:
    # GROQ
    openai:
      api-key:
      base-url: https://api.groq.com/openai

      chat:
        options:
          model:
          temperature:

      embedding:
        base-url: http://localhost:11434
        options:
          model:

    vectorstore:
      chroma:
        client:
          port:

        initialize-schema: true
        tenant-name:
        database-name:
        collection-name: